### ISSUE TITLE
Add initial content to the handbook

### ISSUE THREAD

**Issue by wceolin** [zoonk/handbook#1]
Update the handbook repository with some basic information about this project and how other people can contribute to it. This is important because we'll have some people occasionally helping out in specific tasks, so we need to have some documentation for them to get started.

It's also important that we have information both in Portuguese and English because design and contributors won't necessarily speak Portuguese and content contributors often won't speak English. Therefore, we need to have basic instructions in both languages.

This doesn't need to be a comprehensive guide right now, just some basic information to get us started.

## Tasks

- [x] Explain what this project is, what our values are, and why we are building it.
- [x] Explain how we work asynchronously.
- [x] Explain why we don't have deadlines.
- [x] Explain how to manage tasks.
- [x] Explain how to manage discussions.
- [x] Write a guide on how to start a new project.
- [x] Write a guide on how to configure a new repository.
- [x] Write a guide for non-coders on how to make changes on GitHub.
- [x] Create a repository in Portuguese.
